export const postShape = {
  id: 0,
  uuid: '',
  post_no: '',
  title: '',
  slug: '',
  excerpt: '',
  content: '',
  content_type: '',
  post_category_id: '',
  committee_id: '',
  author_id: '',
  editor_id: '',
  status: '',
  visibility: '',
  is_featured: false,
  allow_on_homepage: false,
  published_at: '',
  featured_image_url: '',
};
